In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv(r'C:\Users\ashis\Courses\Projects\04-Movie-Recomender-System\dataset\tmdb_5000_movies.csv')

In [6]:
df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title                 4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), str(13)
memory usage: 750.6 KB

In [8]:
df.shape

(4803, 20)

In [9]:
print(df.select_dtypes(include='object').columns)
print(df.select_dtypes(include='number').columns)

Index(['genres', 'homepage', 'keywords', 'original_language', 'original_title',
       'overview', 'production_companies', 'production_countries',
       'release_date', 'spoken_languages', 'status', 'tagline', 'title'],
      dtype='str')
Index(['budget', 'id', 'popularity', 'revenue', 'runtime', 'vote_average',
       'vote_count'],
      dtype='str')

Import columns
1. genres
2. title
3. overview
4. keywords
5. id

In [55]:
content_data=df[['genres','title','overview','keywords','tagline','production_companies','production_countries','spoken_languages']]
content_data.shape

(4803, 8)

In [56]:
content_data.sample(4)

,genres,title,overview,keywords,tagline,production_companies,production_countries,spoken_languages
3467,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 27, ""name...",Tales from the Hood,A strange funeral director tells four strange ...,"[{""id"": 378, ""name"": ""prison""}, {""id"": 516, ""n...",Chill or be Chilled,"[{""name"": ""40 Acres & A Mule Filmworks"", ""id"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]"
1867,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",Good Luck Chuck,"Cursed since childhood, dentist Charlie Kagan ...","[{""id"": 572, ""name"": ""sex""}, {""id"": 2269, ""nam...",He has to break his curse before she breaks hi...,"[{""name"": ""Lionsgate"", ""id"": 1632}, {""name"": ""...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...","[{""iso_639_1"": ""en"", ""name"": ""English""}]"
427,"[{""id"": 35, ""name"": ""Comedy""}]",The Hangover Part II,The Hangover crew heads to Thailand for Stu's ...,"[{""id"": 1381, ""name"": ""sun glasses""}, {""id"": 6...",The Wolfpack Is Back,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso..."
1688,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 80, ""nam...",Confessions of a Dangerous Mind,"Television made him famous, but his biggest hi...","[{""id"": 4688, ""name"": ""microfilm""}, {""id"": 556...",Some things are better left top secret.,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]"

In [57]:
content_data.isnull().sum()

genres                  0
title                   0
overview                0
keywords                0
tagline                 0
production_companies    0
production_countries    0
spoken_languages        0
dtype: int64

In [58]:
df['overview'] = df['overview'].fillna("no overview available")
df['tagline'] = df['tagline'].fillna("no tagline available")

In [59]:
content_data.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [60]:
# Extracting text  from the genres column
import ast
def convert_genres(text):
    genres = []
    try:
        for i in ast.literal_eval(text):
            genres.append(i['name'])
    except:
        pass
    return genres
content_data['genres'] = content_data['genres'].apply(convert_genres)
content_data['genres'].head()

0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4             [Action, Adventure, Science Fiction]
Name: genres, dtype: object

In [61]:
content_data.iloc[0].keywords

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [62]:
# extracting text from the keywords column
def extract_keywords(text):
    keywords = []
    for item in ast.literal_eval(text):
        keywords.append(item['name'])
    return keywords
content_data['keywords'] = content_data['keywords'].apply(extract_keywords)

In [64]:
content_data.iloc[0].production_companies

'[{"name": "Ingenious Film Partners", "id": 289}, {"name": "Twentieth Century Fox Film Corporation", "id": 306}, {"name": "Dune Entertainment", "id": 444}, {"name": "Lightstorm Entertainment", "id": 574}]'

In [65]:
# Extracting text from the production_companies column
def extract_production_companies(text):
    companies = []
    for item in ast.literal_eval(text):
        companies.append(item['name'])
    return companies
content_data['production_companies'] = content_data['production_companies'].apply(extract_production_companies)

In [66]:
content_data.iloc[0].production_countries

'[{"iso_3166_1": "US", "name": "United States of America"}, {"iso_3166_1": "GB", "name": "United Kingdom"}]'

In [67]:
# extracting text from the production_companies column
def extract_production_countries(text):
    countries = []
    for item in ast.literal_eval(text):
        countries.append(item['name'])
    return countries
content_data['production_countries'] = content_data['production_countries'].apply(extract_production_countries)

In [68]:
content_data.iloc[0].spoken_languages

'[{"iso_639_1": "en", "name": "English"}, {"iso_639_1": "es", "name": "Espa\\u00f1ol"}]'

In [69]:
# extracting text from the spoken_languages column
def extract_spoken_languages(text):
    languages = []
    for item in ast.literal_eval(text):
        languages.append(item['name'])
    return languages
content_data['spoken_languages'] = content_data['spoken_languages'].apply(extract_spoken_languages)

In [70]:
content_data.head()

,genres,title,overview,keywords,tagline,production_companies,production_countries,spoken_languages
0,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...",Enter the World of Pandora.,"[Ingenious Film Partners, Twentieth Century Fo...","[United States of America, United Kingdom]","[English, Español]"
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","At the end of the world, the adventure begins.","[Walt Disney Pictures, Jerry Bruckheimer Films...",[United States of America],[English]
2,"[Action, Adventure, Crime]",Spectre,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...",A Plan No One Escapes,"[Columbia Pictures, Danjaq, B24]","[United Kingdom, United States of America]","[Français, English, Español, Italiano, Deutsch]"
3,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...",The Legend Ends,"[Legendary Pictures, Warner Bros., DC Entertai...",[United States of America],[English]
4,"[Action, Adventure, Science Fiction]",John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","Lost in our world, found in another.",[Walt Disney Pictures],[United States of America],[English]

In [76]:
# Converting list cols to string
list_cols = [
    'genres',
    'keywords',
    'production_companies',
    'production_countries',
    'spoken_languages'
]

for col in list_cols:
    content_data[col] = content_data[col].apply(
        lambda x: " ".join([i.replace(" ", "") for i in x]) if isinstance(x, list) else str(x)
    )

# Ensuring that cols are string
text_cols = ['overview', 'tagline']

for col in text_cols:
    content_data[col] = content_data[col].apply(str)

In [77]:
# Combing all text data into a single column
content_data['tags'] = (
    content_data['genres'] + " " +
    content_data['overview'] + " " +
    content_data['keywords'] + " " +
    content_data['tagline'] + " " +
    content_data['production_companies'] + " " +
    content_data['production_countries'] + " " +
    content_data['spoken_languages']
)

In [79]:
content_data = content_data[['title', 'tags']]

In [80]:
content_data.head()

,title,tags
0,Avatar,"Action Adventure Fantasy ScienceFiction ['In',..."
1,Pirates of the Caribbean: At World's End,"Adventure Fantasy Action ['Captain', 'Barbossa..."
2,Spectre,"Action Adventure Crime ['A', 'cryptic', 'messa..."
3,The Dark Knight Rises,"Action Crime Drama Thriller ['Following', 'the..."
4,John Carter,"Action Adventure ScienceFiction ['John', 'Cart..."

In [85]:
# creating idx for movie titles
content_data = content_data.reset_index(drop=True)

idx = pd.Series(content_data.index, index=content_data['title']).drop_duplicates()

content_data['movie_index'] = content_data.index

In [86]:
content_data

,title,tags,movie_index
0,Avatar,"Action Adventure Fantasy ScienceFiction ['In',...",0
1,Pirates of the Caribbean: At World's End,"Adventure Fantasy Action ['Captain', 'Barbossa...",1
2,Spectre,"Action Adventure Crime ['A', 'cryptic', 'messa...",2
3,The Dark Knight Rises,"Action Crime Drama Thriller ['Following', 'the...",3
4,John Carter,"Action Adventure ScienceFiction ['John', 'Cart...",4
...,...,...,...
4798,El Mariachi,"Action Crime Thriller ['El', 'Mariachi', 'just...",4798
4799,Newlyweds,"Comedy Romance ['A', 'newlywed', ""couple's"", '...",4799
4800,"Signed, Sealed, Delivered","Comedy Drama Romance TVMovie ['""Signed,', 'Sea...",4800
4801,Shanghai Calling,"['When', 'ambitious', 'New', 'York', 'attorne...",4801
4802,My Date with Drew,"Documentary ['Ever', 'since', 'the', 'second',...",4802

# Natural Language Processing

In [130]:
import re
import string
def clean_text(text):
    text = str(text)               # ensure string
    text = text.lower()           # lowercase
    text = re.sub(r'\d+', '', text)  # remove numbers
    text = text.translate(str.maketrans('', '', string.punctuation))  # punctuation removal
    text = " ".join(text.split())  # extra spaces removal
    return text
content_data['tags'] = content_data['tags'].apply(clean_text)

In [131]:
# Lower case the movie titles
def lower_case(text):
    return text.lower()
content_data['title'] = content_data['title'].apply(lower_case)

In [132]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stem_text(text):
    words = text.split()
    return " ".join([ps.stem(word) for word in words])
content_data['tags'] = content_data['tags'].apply(stem_text)

In [133]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')
vectors = vectorizer.fit_transform(content_data['tags']).toarray()

In [134]:
print(vectors.shape)
print(vectorizer.get_feature_names_out())
print(vectorizer.get_metadata_routing())
print(vectorizer.get_stop_words())
print(vectorizer.get_params())

(4803, 5000)
['aaron' 'abandon' 'abbi' ... '日本語' '普通话' '한국어조선말']
{}
frozenset({'amount', 'either', 'its', 'have', 'always', 'nine', 'twenty', 'those', 'any', 'serious', 'upon', 'perhaps', 'hereafter', 'full', 'afterwards', 'beyond', 'who', 'same', 'detail', 'thereby', 'thereupon', 'cry', 'forty', 'ours', 'nothing', 'see', 'anywhere', 'two', 'in', 'become', 'indeed', 'together', 'here', 'neither', 'therefore', 'then', 'yourself', 'go', 'what', 'fifteen', 'found', 'there', 'even', 'eight', 'over', 'seem', 'i', 'from', 'for', 'she', 'none', 'enough', 'under', 'else', 'noone', 'around', 'moreover', 'put', 'yet', 'five', 'himself', 'sixty', 'with', 'could', 'very', 'across', 'an', 'not', 'after', 'ie', 'ten', 'except', 'fifty', 'etc', 'alone', 'bottom', 'every', 'well', 'he', 'so', 'done', 'were', 'thus', 'already', 'that', 'becoming', 'you', 'everything', 'at', 'through', 'myself', 'mill', 'give', 'hereupon', 'is', 'each', 'fill', 'itself', 'should', 'whereafter', 'if', 'elsewhere', 'empty', 'third', 'de', 'whose', 'these', 'co', 'first', 'whom', 'get', 'three', 'am', 'own', 'down', 'made', 'ourselves', 'cant', 'ever', 'me', 'inc', 'no', 'find', 'almost', 'less', 'ltd', 'against', 'been', 'anyhow', 'much', 'anyone', 'eg', 'on', 'please', 'couldnt', 'fire', 'because', 'off', 'but', 'within', 'whence', 'many', 'whenever', 'seemed', 'without', 'why', 'might', 'show', 'latterly', 'herein', 'others', 'describe', 'former', 'amongst', 'part', 'will', 'too', 'was', 'our', 'hasnt', 're', 'thick', 'their', 'wherein', 'hereby', 'throughout', 'another', 'mostly', 'call', 'must', 'yours', 'besides', 'beside', 'before', 'both', 'now', 'until', 'the', 'and', 'a', 'than', 'had', 'latter', 'twelve', 'are', 'being', 'how', 'of', 'rather', 'though', 'when', 'once', 'where', 'whole', 'behind', 'be', 'anything', 'often', 'four', 'due', 'would', 'someone', 'along', 'further', 'again', 'your', 'somewhere', 'him', 'cannot', 'therein', 'some', 'thru', 'herself', 'beforehand', 'hence', 'anyway', 'whereas', 'becomes', 'up', 'into', 'last', 'sincere', 'it', 'thereafter', 'among', 'although', 'con', 'they', 'seeming', 'amoungst', 'can', 'all', 'during', 'whither', 'otherwise', 'we', 'something', 'however', 'most', 'nor', 'whether', 'still', 'while', 'six', 'themselves', 'nobody', 'also', 'wherever', 'one', 'us', 'via', 'whoever', 'back', 'system', 'interest', 'by', 'whereby', 'out', 'them', 'mine', 'onto', 'his', 'top', 'un', 'hers', 'sometimes', 'as', 'has', 'eleven', 'such', 'towards', 'which', 'move', 'only', 'or', 'never', 'her', 'name', 'namely', 'thence', 'sometime', 'everyone', 'nevertheless', 'several', 'between', 'somehow', 'next', 'below', 'more', 'this', 'do', 'take', 'since', 'to', 'bill', 'other', 'yourselves', 'toward', 'side', 'became', 'nowhere', 'above', 'per', 'whatever', 'meanwhile', 'few', 'seems', 'thin', 'front', 'keep', 'whereupon', 'may', 'formerly', 'everywhere', 'least', 'about', 'my', 'hundred'})
{'analyzer': 'word', 'binary': False, 'decode_error': 'strict', 'dtype': <class 'numpy.float64'>, 'encoding': 'utf-8', 'input': 'content', 'lowercase': True, 'max_df': 1.0, 'max_features': 5000, 'min_df': 1, 'ngram_range': (1, 1), 'norm': 'l2', 'preprocessor': None, 'smooth_idf': True, 'stop_words': 'english', 'strip_accents': None, 'sublinear_tf': False, 'token_pattern': '(?u)\\b\\w\\w+\\b', 'tokenizer': None, 'use_idf': True, 'vocabulary': None}

In [135]:
vectors[0]

array([0., 0., 0., ..., 0., 0., 0.], shape=(5000,))

In [136]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)

In [137]:
similarity

array([[1.        , 0.0370577 , 0.05369986, ..., 0.04656525, 0.00602338,
        0.00184777],
       [0.0370577 , 1.        , 0.02325747, ..., 0.02634484, 0.01383734,
        0.00843535],
       [0.05369986, 0.02325747, 1.        , ..., 0.02370006, 0.00192211,
        0.00218696],
       ...,
       [0.04656525, 0.02634484, 0.02370006, ..., 1.        , 0.01446138,
        0.03026398],
       [0.00602338, 0.01383734, 0.00192211, ..., 0.01446138, 1.        ,
        0.01682305],
       [0.00184777, 0.00843535, 0.00218696, ..., 0.03026398, 0.01682305,
        1.        ]], shape=(4803, 4803))

In [138]:
similarity.shape

(4803, 4803)

In [146]:
def recommend_df(movie, top_n=5):

    # normalize input
    movie = movie.strip().lower()

    # create lowercase mapping of idx
    idx_lower = {k.lower(): v for k, v in idx.items()}

    # check existence
    if movie not in idx_lower:
        return "Movie not found in dataset"

    movie_index = idx_lower[movie]
    distances = similarity[movie_index]

    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:top_n+1]

    data = []

    for i, score in movie_list:
        data.append({
            "Movie": content_data.iloc[i].title,
            "Similarity": round(float(score), 3)
        })

    return pd.DataFrame(data)

In [150]:
result = recommend_df("pirates of the Caribbean: at world's end")
print(result)

                                               Movie  Similarity
0         pirates of the caribbean: dead man's chest       0.274
1        pirates of the caribbean: on stranger tides       0.239
2  pirates of the caribbean: the curse of the bla...       0.212
3                                         life of pi       0.194
4      the pirates! in an adventure with scientists!       0.186

In [151]:
import pickle

pickle.dump(vectorizer, open("tfidf_vectorizer.pkl", "wb"))
pickle.dump(similarity, open("similarity_matrix.pkl", "wb"))
pickle.dump(content_data, open("content_data.pkl", "wb"))
pickle.dump(idx, open("idx.pkl", "wb"))